'use strict';const PlayerId="bilibiliPlayer",PlayerContainerId="bilibili-player",VQ=`#${PlayerId} video`;var LongStep=30;class TryCount{constructor(a,b,c){this.max=a;this.fn=c;this.timeout=b;this.count=0;this.repeat=this.start.bind(this)}start(){this.count++;this.count>this.max||this.fn()||setTimeout(this.repeat,this.timeout)}}function getDanmuBtn(){return document.querySelector(".bilibili-player-video-danmaku-switch > input[type=checkbox]")}
function formatTime(a){let b=Math.floor(a/60);a%=60;return`${10>b?"0"+b:b}:${10>a?"0"+a:a}`}var StatusPanel,StatusPanelTimeoutID,TimePanel,TimePanelTimeoutID,ClockPanel,ClockPanelTimeoutID,ClockFormat,TitlePanel;
class StateInfo{static showState(a){if(!StatusPanel){var b=document.createElement("div");b.style.cssText="position: absolute; z-index: 100000; left: 34px; bottom: 80px; padding: 10px; background-color: black; color: white; font-size: 30px;";StatusPanel=b}if(b=document.querySelector(".bilibili-player-video-state"))StatusPanel.innerText=a,StatusPanel.style.display="block",b.parentElement.appendChild(StatusPanel),StatusPanelTimeoutID&&clearTimeout(StatusPanelTimeoutID),StatusPanelTimeoutID=setTimeout(StateInfo.clearState,
1500)}static clearState(){StatusPanelTimeoutID=null;StatusPanel&&(StatusPanel.style.display="none")}static showDanmuState(){let a=getDanmuBtn();a&&StateInfo.showState(`\u5f39\u5e55 ${a.checked?"On":"Off"}`)}static toggleTimeState(){if(TimePanelTimeoutID)clearTimeout(TimePanelTimeoutID),TimePanelTimeoutID=null,TimePanel&&(TimePanel.style.display="none");else{if(!TimePanel){let a=document.createElement("div");a.style.cssText="position: absolute; z-index: 100000; left: 0px; top: 0px; padding: 4px; background-color: rgba(8, 8, 8, 0.75); color: white; font-family: monospace; font-size: 22px;";
TimePanel=a}StateInfo.showPlayerTime(!0)}}static showPlayerTime(a=!1){var b=document.querySelector(VQ);let c=document.querySelector(".bilibili-player-video-state");if(c&&b&&0!==b.readyState&&Number.isFinite(b.duration)){var d=Math.round(b.currentTime);b=Math.round(b.duration);d=`${formatTime(d)} / ${formatTime(b)} [-${formatTime(b-d)}]`;a&&(TimePanel.style.display="block");c.parentElement!==TimePanel.parentElement&&c.parentElement.appendChild(TimePanel);TimePanel.innerText=d;TimePanelTimeoutID=setTimeout(StateInfo.showPlayerTime,
1E3)}else TimePanelTimeoutID=null,TimePanel.style.display="none"}static toggleClockState(){if(ClockPanelTimeoutID)clearTimeout(ClockPanelTimeoutID),ClockPanelTimeoutID=null,ClockPanel&&(ClockPanel.style.display="none");else{if(!ClockPanel){var a={hour12:!0,hour:"2-digit",minute:"2-digit"};settings&&(a.hour12=!settings.timeFormatHour24,settings.timeFormatSecond&&(a.second="2-digit"));ClockFormat=new Intl.DateTimeFormat("en-GB",a);a=document.createElement("div");a.style.cssText="position: absolute; z-index: 100000; right: 0px; top: 0px; padding: 4px; background-color: rgba(8, 8, 8, 0.75); color: white; font-family: monospace; font-size: 22px;";
ClockPanel=a}StateInfo.showClockTime(!0)}}static showClockTime(a=!1){let b=document.querySelector(".bilibili-player-video-state");b?(ClockPanel.innerText=ClockFormat.format(new Date),a&&(ClockPanel.style.display="block"),b.parentElement!==ClockPanel.parentElement&&b.parentElement.appendChild(ClockPanel),ClockPanelTimeoutID=setTimeout(StateInfo.showClockTime,1E3)):(ClockPanelTimeoutID=null,ClockPanel.style.display="none")}static showTitle(){if(!TitlePanel){var a=document.createElement("div");a.style.cssText=
"display: none; position: absolute; z-index: 100000; top: 0px; left: 50%; transform: translateX(-50%); padding: 4px 8px; background-color: rgba(8, 8, 8, 0.75); color: white; font-size: 22px;";TitlePanel=a}a=document.querySelector(".bilibili-player-video-state");let b=document.querySelector(".bilibili-player-video-top-title");a&&b&&b.textContent?(a.parentElement!==TitlePanel.parentElement&&(a.parentElement.appendChild(TitlePanel),TitlePanel.style.display="none"),"none"==TitlePanel.style.display?(TitlePanel.innerText=
b.textContent,TitlePanel.style.display="block"):TitlePanel.style.display="none"):TitlePanel.style.display="none"}}function closeDanmaku(){(new TryCount(videoPage?40:20,500,function(){let a=getDanmuBtn();return a?(a.checked&&a.click(),!0):!1})).start()}
function setScreenMode(a){(new TryCount(videoPage?40:20,500,function(){if(1===a&&document.body.classList.contains("player-mode-widescreen")||2===a&&document.body.classList.contains("player-mode-webfullscreen"))return!0;let b;1===a?b=document.querySelector(".bilibili-player-video-btn-widescreen"):2===a&&(b=document.querySelector(".bilibili-player-video-web-fullscreen"));return b?(b.click(),!0):!1})).start()}var lastScreenMode=0;
function fullscreenchange(a){document.fullscreenElement?lastScreenMode=document.body.classList.contains("player-mode-webfullscreen")?2:document.body.classList.contains("player-mode-widescreen")?1:0:0!=lastScreenMode&&(""==document.body.className&&1===lastScreenMode?setScreenMode(lastScreenMode):setTimeout(()=>setScreenMode(lastScreenMode),0))}
function videoEnd(){document.fullscreenElement&&setTimeout(function(){let a=document.querySelector(VQ);a&&a.ended&&document.fullscreenElement&&document.exitFullscreen()},600)}function playNext(){let a=document.querySelector(".bilibili-player-video-btn-next");a&&a.click()}function autoplayVideo(a){a||(a=document.querySelector(VQ));let b=!1;try{b=window.self!==window.top}catch(c){b=!0}b?"1"==(new URL(location.href)).searchParams.get("autoplay")&&a&&a.play().catch(c=>{}):a&&a.play().catch(c=>{})}
function scaleVideo(a){let b=document.querySelector(VQ);if(b){let c=b.style.width;""==c&&(c="100%");b.style.width=0<a?"50%"==c?"75%":"100%":0>a?"100%"==c?"75%":"50%":"100%";b.style.margin="auto"}}
async function keyboardListener(a){var b=a.target.tagName;if(!("INPUT"===b||"TEXTAREA"===b||a.target.isContentEditable||a.ctrlKey||a.altKey||a.metaKey)){b=a.keyCode;var c=a.code;if(70===b)a.preventDefault(),a.stopPropagation(),document.pictureInPictureElement&&await document.exitPictureInPicture(),(a=document.querySelector(".bilibili-player-video-btn-fullscreen"))&&a.click();else if(87===b)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(".bilibili-player-video-web-fullscreen"))&&
a.click();else if(68===b)if(a.preventDefault(),a.stopPropagation(),a.shiftKey)StateInfo.showDanmuState();else{if(a=getDanmuBtn())a.click(),StateInfo.showDanmuState()}else if(84===b)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(".bilibili-player-video-btn-widescreen"))&&a.click();else if(75===b)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(".bilibili-player-video-btn-start"))&&a.click();else if(74===b)a.preventDefault(),a.stopPropagation(),a.shiftKey?seek(!1,LongStep):
defaultSeek(!1);else if(76===b)a.preventDefault(),a.stopPropagation(),a.shiftKey?seek(!0,LongStep):defaultSeek(!0);else if("Equal"===c)a.preventDefault(),a.stopPropagation(),a.shiftKey?scaleVideo(1):((a=document.querySelector(VQ))&&5>a.playbackRate&&(a.playbackRate+=.25),a&&StateInfo.showState(chrome.i18n.getMessage("stateSpeed",[a.playbackRate])));else if("Minus"===c)a.preventDefault(),a.stopPropagation(),a.shiftKey?scaleVideo(-1):((a=document.querySelector(VQ))&&.25<a.playbackRate&&(a.playbackRate-=
.25),a&&StateInfo.showState(chrome.i18n.getMessage("stateSpeed",[a.playbackRate])));else if("Digit0"===c)if(a.preventDefault(),a.stopPropagation(),a.shiftKey)scaleVideo(0);else{if(a=document.querySelector(VQ))a.playbackRate=1,StateInfo.showState(chrome.i18n.getMessage("stateSpeed",[1]))}else if(67===b)a.preventDefault(),a.stopPropagation(),toggleCaption();else if(73===b)a.preventDefault(),a.stopPropagation(),Light.toggle(0);else if(78===b)a.preventDefault(),a.stopPropagation(),playNext();else if(77===
b){if(a.preventDefault(),a.stopPropagation(),a=document.querySelector(".bilibili-player-video-btn-volume"))if(a.firstElementChild.click(),a=document.querySelector(VQ))a=a.muted?chrome.i18n.getMessage("stateMute"):chrome.i18n.getMessage("stateUnmute"),StateInfo.showState(a)}else 80===b?(a.preventDefault(),a.stopPropagation(),togglePIP()):188===b?(a.preventDefault(),a.stopPropagation(),seek(!1,.042)):190===b?(a.preventDefault(),a.stopPropagation(),seek(!0,.042)):83===b&&a.shiftKey?(a.preventDefault(),
a.stopPropagation(),screenshot()):71===b?(a.preventDefault(),a.stopPropagation(),StateInfo.toggleTimeState()):72===b?(a.preventDefault(),a.stopPropagation(),StateInfo.toggleClockState()):66===b&&(a.preventDefault(),a.stopPropagation(),StateInfo.showTitle())}}function setupMediaKeys(){if("mediaSession"in navigator)try{navigator.mediaSession.setActionHandler("nexttrack",playNext)}catch(a){}}setupMediaKeys();
function seek(a,b){let c=document.querySelector(VQ);!c||0===c.readyState||!Number.isFinite(c.duration)||1>b&&!c.paused||(a?c.currentTime=Math.min(c.currentTime+b,c.duration-1):c.duration==c.currentTime?defaultSeek(!1):c.currentTime=Math.max(c.currentTime-b,0))}
function defaultSeek(a){let b=document.querySelector(".bilibili-player-video-wrap");b&&b.click();a=a?new KeyboardEvent("keydown",{bubbles:!0,cancelable:!0,key:"ArrowRight",code:"ArrowRight",keyCode:39}):new KeyboardEvent("keydown",{bubbles:!0,cancelable:!0,key:"ArrowLeft",code:"ArrowLeft",keyCode:37});document.body.dispatchEvent(a)}
async function togglePIP(){let a=document.querySelector(VQ);a&&document.pictureInPictureEnabled&&!a.disablePictureInPicture&&0!==a.readyState&&(document.fullscreenElement&&await document.exitFullscreen(),document.pictureInPictureElement?document.exitPictureInPicture():a.requestPictureInPicture())}
class Light{static clickLightBtn(a){let b=document.querySelector(".bilibili-player-video-btn-setting-right-others-content-lightoff input[type=checkbox]")||document.querySelector(".bilibili-player-video-btn-setting-panel-others-content-lightoff input[type=checkbox]");return b?(0===a?b.click():1===a&&b.checked?b.click():2!==a||b.checked||b.click(),!0):!1}static toggle(a){if(Light.clickLightBtn(a))return!0;{let b=document.querySelector(".bilibili-player-video-btn-setting");return b?(b.addEventListener("mouseover",
c=>{b.dispatchEvent(new MouseEvent("mouseout"));setTimeout(()=>Light.clickLightBtn(a),100)},{once:!0}),b.dispatchEvent(new MouseEvent("mouseover")),!0):!1}}static initTurnOffLight(){(new TryCount(videoPage?30:15,600,()=>Light.toggle(2))).start()}static smartCallback(a,b){a=a[0];a.isIntersecting?a.target.classList.contains("mini-player")||Light.toggle(2):Light.toggle(1)}static smartLight(){let a=new IntersectionObserver(Light.smartCallback,{threshold:.75}),b=document.getElementById(PlayerContainerId);
b&&a.observe(b)}}function toggleCaption(){let a=document.querySelector(".bilibili-player-iconfont-subtitle");if(a)if(a.nextElementSibling)a.click();else{let b=a.parentElement;b.addEventListener("mouseover",c=>{setTimeout(()=>{b.dispatchEvent(new MouseEvent("mouseout"));setTimeout(()=>a.click(),500)},150)},{once:!0});b.dispatchEvent(new MouseEvent("mouseover"))}}var canvas,file;
function screenshot(){let a=document.querySelector(VQ);!a||2>a.readyState||(canvas||(canvas=document.createElement("canvas")),canvas.width=a.videoWidth,canvas.height=a.videoHeight,canvas.getContext("2d").drawImage(a,0,0,canvas.width,canvas.height),file||(file=document.createElement("a")),file.download=`screenshot-${a.currentTime.toFixed(3)}.jpg`,file.href=canvas.toDataURL("image/jpeg",.98),file.click())}
function changeDanmuHeight(){let a=document.querySelector(".bilibili-player-video-danmaku");var b=document.querySelector(VQ);if(a&&b){var c=b.clientHeight;b=a.parentElement.clientHeight;c=.85*c+(b-c)/2;b=`${(c/b*100).toFixed(2)}%`;c=Math.round(c*devicePixelRatio);a.style.height!=b&&(a.style.height=b);"CANVAS"===a.tagName&&a.height!=c&&(a.height=c)}}var resizeObserver;
function preventShade(){let a=document.querySelector(".bilibili-player-video-danmaku");a&&(changeDanmuHeight(),resizeObserver=new ResizeObserver(()=>{setTimeout(changeDanmuHeight,1E3)}),resizeObserver.observe(a.parentElement))}
function observeVideo(){function a(){let e=document.getElementById(PlayerId);e&&(c=new MutationObserver(onVideoChanged),c.observe(e,b))}const b={childList:!0};let c;a();let d=document.getElementById(PlayerContainerId);d&&(new MutationObserver(function(){c.disconnect();setTimeout(a,800);onVideoChanged()})).observe(d,b)}
function onVideoChanged(){settings.turnOffDanmu&&closeDanmaku();settings.preventshade&&(resizeObserver&&resizeObserver.disconnect(),setTimeout(preventShade,500));settings.autoplay&&setTimeout(autoplayVideo,500);settings.exitFullscreen&&setTimeout(function(){let a=document.querySelector(VQ);a&&a.addEventListener("ended",videoEnd)},2E3);TitlePanel&&"none"!=TitlePanel.style.display&&setTimeout(StateInfo.showTitle,1500)}
function waitVideoLoad(){(new TryCount(videoPage?60:30,600,function(){let a=document.querySelector(VQ);return a?(observeVideo(),initState(a),!0):!1})).start()}function isVideoPage(){const a=location.href;return a.startsWith("https://www.bilibili.com/video/")||a.startsWith("https://www.bilibili.com/bangumi/")}var videoPage=isVideoPage(),settings;
function init(){chrome.storage.sync.get({keyboard:!0,turnOffDanmu:!0,screenMode:0,autoplay:!1,exitFullscreen:!1,preventshade:!1,turnOffLight:!1,smartLight:!1,longStep:30,timeFormatHour24:!1,timeFormatSecond:!1},init2)}function init2(a){settings=a;waitVideoLoad()}
function initState(a){settings.keyboard&&document.addEventListener("keydown",keyboardListener);settings.turnOffDanmu&&closeDanmaku();let b=settings.screenMode;0!==b&&setScreenMode(b);settings.autoplay&&autoplayVideo(a);settings.turnOffLight&&(Light.initTurnOffLight(),settings.smartLight&&Light.smartLight());settings.preventshade&&preventShade();LongStep=settings.longStep;document.addEventListener("fullscreenchange",fullscreenchange);settings.exitFullscreen&&a.addEventListener("ended",videoEnd)}
var started=!1;document.hidden?document.addEventListener("visibilitychange",function(){document.hidden||started||(started=!0,init())}):init();
