'use strict';const PlayerId="bilibiliPlayer",PlayerContainerId="bilibili-player",VQ=`#${PlayerId} video`;var LongStep=30;class TryCount{constructor(a,b,c){this.max=a;this.fn=c;this.timeout=b;this.count=0;this.repeat=this.start.bind(this)}start(){this.count++;this.count>this.max||this.fn()||setTimeout(this.repeat,this.timeout)}}function getDanmuBtn(){return document.querySelector(".bilibili-player-video-danmaku-switch > input[type=checkbox]")}
function closeDanmaku(){(new TryCount(videoPage?40:20,500,function(){let a=getDanmuBtn();return a?(a.checked&&a.click(),!0):!1})).start()}
function setScreenMode(a){(new TryCount(videoPage?40:20,500,function(){if(1===a&&document.body.classList.contains("player-mode-widescreen")||2===a&&document.body.classList.contains("player-mode-webfullscreen"))return!0;let b;1===a?b=document.querySelector(".bilibili-player-video-btn-widescreen"):2===a&&(b=document.querySelector(".bilibili-player-video-web-fullscreen"));return b?(b.click(),!0):!1})).start()}var lastScreenMode=0;
function fullscreenchange(a){document.fullscreenElement?lastScreenMode=document.body.classList.contains("player-mode-webfullscreen")?2:document.body.classList.contains("player-mode-widescreen")?1:0:0!=lastScreenMode&&(""==document.body.className&&1===lastScreenMode?setScreenMode(lastScreenMode):setTimeout(()=>setScreenMode(lastScreenMode),0))}
function videoEnd(){document.fullscreenElement&&setTimeout(function(){let a=document.querySelector(VQ);a&&a.ended&&document.fullscreenElement&&document.exitFullscreen()},600)}function playNext(){let a=document.querySelector(".bilibili-player-video-btn-next");a&&a.click()}function playVideo(a){a||(a=document.querySelector(VQ));a&&a.play().catch(b=>{})}
async function keyboardListener(a){var b=a.target.tagName;if("INPUT"!==b&&"TEXTAREA"!==b&&!(a.ctrlKey||a.altKey||a.metaKey)){b=a.keyCode;var c=a.code;if(70===b)a.preventDefault(),a.stopPropagation(),document.pictureInPictureElement&&await document.exitPictureInPicture(),(a=document.querySelector(".bilibili-player-video-btn-fullscreen"))&&a.click();else if(87===b)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(".bilibili-player-video-web-fullscreen"))&&a.click();else if(68===b){if(a.preventDefault(),
a.stopPropagation(),a=getDanmuBtn())if(a.click(),a=document.querySelector(".bilibili-player-danmaku-setting-lite-panel"))a.style.display="none"}else if(84===b)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(".bilibili-player-video-btn-widescreen"))&&a.click();else if(75===b)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(".bilibili-player-video-btn-start"))&&a.click();else if(74===b)a.preventDefault(),a.stopPropagation(),a.shiftKey?seek(!1,LongStep):defaultSeek(!1);
else if(76===b)a.preventDefault(),a.stopPropagation(),a.shiftKey?seek(!0,LongStep):defaultSeek(!0);else if("Equal"===c)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(VQ))&&5>a.playbackRate&&(a.playbackRate+=.25);else if("Minus"===c)a.preventDefault(),a.stopPropagation(),(a=document.querySelector(VQ))&&.25<a.playbackRate&&(a.playbackRate-=.25);else if("Digit0"===c){if(a.preventDefault(),a.stopPropagation(),a=document.querySelector(VQ))a.playbackRate=1}else 67===b?(a.preventDefault(),
a.stopPropagation(),toggleCaption()):73===b?(a.preventDefault(),a.stopPropagation(),Light.toggle(0)):78===b?(a.preventDefault(),a.stopPropagation(),playNext()):77===b?(a.preventDefault(),a.stopPropagation(),(a=document.querySelector(".bilibili-player-video-btn-volume"))&&a.firstElementChild.click()):80===b?(a.preventDefault(),a.stopPropagation(),togglePIP()):188===b?(a.preventDefault(),a.stopPropagation(),seek(!1,.042)):190===b?(a.preventDefault(),a.stopPropagation(),seek(!0,.042)):83===b&&a.shiftKey&&
(a.preventDefault(),a.stopPropagation(),screenshot())}}function setupMediaKeys(){if("mediaSession"in navigator)try{navigator.mediaSession.setActionHandler("nexttrack",playNext)}catch(a){}}setupMediaKeys();function seek(a,b){let c=document.querySelector(VQ);!c||0===c.readyState||!Number.isFinite(c.duration)||1>b&&!c.paused||(a?c.currentTime=Math.min(c.currentTime+b,c.duration-1):c.duration==c.currentTime?defaultSeek(!1):c.currentTime=Math.max(c.currentTime-b,0))}
function defaultSeek(a){let b=document.querySelector(".bilibili-player-video-wrap");b&&b.click();a=a?new KeyboardEvent("keydown",{bubbles:!0,cancelable:!0,key:"ArrowRight",code:"ArrowRight",keyCode:39}):new KeyboardEvent("keydown",{bubbles:!0,cancelable:!0,key:"ArrowLeft",code:"ArrowLeft",keyCode:37});document.body.dispatchEvent(a)}
async function togglePIP(){let a=document.querySelector(VQ);a&&document.pictureInPictureEnabled&&!a.disablePictureInPicture&&0!==a.readyState&&(document.fullscreenElement&&await document.exitFullscreen(),document.pictureInPictureElement?document.exitPictureInPicture():a.requestPictureInPicture())}
class Light{static clickLightBtn(a){let b=document.querySelector(".bilibili-player-video-btn-setting-right-others-content-lightoff input[type=checkbox]")||document.querySelector(".bilibili-player-video-btn-setting-panel-others-content-lightoff input[type=checkbox]");return b?(0===a?b.click():1===a&&b.checked?b.click():2!==a||b.checked||b.click(),!0):!1}static toggle(a){if(Light.clickLightBtn(a))return!0;{let b=document.querySelector(".bilibili-player-video-btn-setting");return b?(b.addEventListener("mouseover",
c=>{b.dispatchEvent(new MouseEvent("mouseout"));setTimeout(()=>Light.clickLightBtn(a),100)},{once:!0}),b.dispatchEvent(new MouseEvent("mouseover")),!0):!1}}static initTurnOffLight(){(new TryCount(videoPage?30:15,600,()=>Light.toggle(2))).start()}static smartCallback(a,b){a=a[0];a.isIntersecting?a.target.classList.contains("mini-player")||Light.toggle(2):Light.toggle(1)}static smartLight(){let a=new IntersectionObserver(Light.smartCallback,{threshold:.75}),b=document.getElementById(PlayerContainerId);
b&&a.observe(b)}}function toggleCaption(){let a=document.querySelector(".bilibili-player-iconfont-subtitle");if(a)if(a.nextElementSibling)a.click();else{let b=a.parentElement;b.addEventListener("mouseover",c=>{setTimeout(()=>{b.dispatchEvent(new MouseEvent("mouseout"));setTimeout(()=>a.click(),500)},150)},{once:!0});b.dispatchEvent(new MouseEvent("mouseover"))}}var canvas,file;
function screenshot(){let a=document.querySelector(VQ);!a||2>a.readyState||(canvas||(canvas=document.createElement("canvas")),canvas.width=a.videoWidth,canvas.height=a.videoHeight,canvas.getContext("2d").drawImage(a,0,0,canvas.width,canvas.height),file||(file=document.createElement("a")),file.download=`screenshot-${a.currentTime.toFixed(3)}.jpg`,file.href=canvas.toDataURL("image/jpeg",.98),file.click())}
function changeDanmuHeight(){let a=document.querySelector(".bilibili-player-video-danmaku");var b=document.querySelector(VQ);if(a&&b){var c=b.clientHeight;b=a.parentElement.clientHeight;c=.85*c+(b-c)/2;b=`${(c/b*100).toFixed(2)}%`;c=Math.round(c*devicePixelRatio);a.style.height!=b&&(a.style.height=b);"CANVAS"===a.tagName&&a.height!=c&&(a.height=c)}}var resizeObserver;
function preventShade(){let a=document.querySelector(".bilibili-player-video-danmaku");a&&(changeDanmuHeight(),resizeObserver=new ResizeObserver(()=>{setTimeout(changeDanmuHeight,1E3)}),resizeObserver.observe(a.parentElement))}
function observeVideo(){function a(){let d=document.getElementById(PlayerId);d&&(c=new MutationObserver(onVideoChanged),c.observe(d,b))}const b={childList:!0};let c;a();let e=document.getElementById(PlayerContainerId);e&&(new MutationObserver(function(){c.disconnect();setTimeout(a,800);onVideoChanged()})).observe(e,b)}
function onVideoChanged(){settings.turnOffDanmu&&closeDanmaku();settings.preventshade&&(resizeObserver&&resizeObserver.disconnect(),setTimeout(preventShade,500));settings.autoplay&&setTimeout(playVideo,500);settings.exitFullscreen&&setTimeout(function(){let a=document.querySelector(VQ);a&&a.addEventListener("ended",videoEnd)},2E3)}function waitVideoLoad(){(new TryCount(videoPage?60:30,600,function(){let a=document.querySelector(VQ);return a?(observeVideo(),initState(a),!0):!1})).start()}
function isVideoPage(){const a=location.href;return a.startsWith("https://www.bilibili.com/video/")||a.startsWith("https://www.bilibili.com/bangumi/")}var videoPage=isVideoPage(),settings;function init(){chrome.storage.sync.get({keyboard:!0,turnOffDanmu:!0,screenMode:0,autoplay:!1,exitFullscreen:!1,preventshade:!1,turnOffLight:!1,smartLight:!1,longStep:30},init2)}function init2(a){settings=a;waitVideoLoad()}
function initState(a){settings.keyboard&&document.addEventListener("keydown",keyboardListener);settings.turnOffDanmu&&closeDanmaku();let b=settings.screenMode;0!==b&&setScreenMode(b);settings.autoplay&&playVideo(a);settings.turnOffLight&&(Light.initTurnOffLight(),settings.smartLight&&Light.smartLight());settings.preventshade&&preventShade();LongStep=settings.longStep;document.addEventListener("fullscreenchange",fullscreenchange);settings.exitFullscreen&&a.addEventListener("ended",videoEnd)}
var started=!1;document.hidden?document.addEventListener("visibilitychange",function(){document.hidden||started||(started=!0,init())}):init();
