distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Tue Feb  2 01:32:14 2021"
installation_id: "7ebcd318-77d0-484b-bd5a-749f27bb0be8"
rime_version: 1.7.0